### ISSUE TITLE
Please add an open source license

### ISSUE THREAD

**Issue by dpsanders** [skissler/nCoV_introduction#1]
Please add an open source license, preferably the [MIT license](https://opensource.org/licenses/MIT), so that people can look at and use the code.

**Comment by skissler** [comment]
Thanks for the notification - that's done!

Best wishes,
Stephen


Stephen Kissler
Postdoctoral Fellow, Harvard School of Public Health
Dept. of Immunology and Infectious Diseases
skissler@hsph.harvard.edu

**Comment by dpsanders** [comment]
Thanks but I don't see the license file in the repo?

**Comment by dpsanders** [comment]
Also you should add a brief README explaining the content of the repo and with a link to the paper.

**Comment by skissler** [comment]
Hi David,

Thanks for catching those things - that should be updated now!

Best wishes,
Stephen


Stephen Kissler
Postdoctoral Fellow, Harvard School of Public Health
Dept. of Immunology and Infectious Diseases
skissler@hsph.harvard.edu

**Comment by dpsanders** [comment]
Thanks, looks good!
